version: 1
disable_existing_loggers: False

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/app.log
    encoding: utf8

loggers:
  dev:
    level: DEBUG
    handlers: [console, file]
    propagate: no

  prod:
    level: INFO
    handlers: [file]
    propagate: no

root:
  level: INFO
  handlers: [console, file]
